<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

    public function getSuperChien()
    {
        $q = $this->_em->createQueryBuilder()
            ->select('post')
            ->from('AppBundle:Post', 'post')
        ;

        $q->where('post.public = :active' )->setParameter('active', true);

        return $q->getQuery()->getResult();
    }

}
